name: SDK Release Notification

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  notify-sdks:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Python SDK
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CROSS_REPO_READ_PAT }}
          repository: Universal-Commerce-Protocol/python-sdk
          event-type: spec-release
          client-payload: '{"version": "${{ github.ref_name }}"}'

      - name: Notify JavaScript SDK
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CROSS_REPO_READ_PAT }}
          repository: Universal-Commerce-Protocol/js-sdk
          event-type: spec-release
          client-payload: '{"version": "${{ github.ref_name }}"}'
